namespace Magpie {
	runtimeclass ScalingModeParameter : Windows.UI.Xaml.Data.INotifyPropertyChanged {
		Boolean IsBoolean { get; };
		Boolean IsFloat { get; };
		Boolean IsVisible { get; };
		Boolean BooleanValue;
		Double Value;
		String Label { get; };
		String ValueText { get; };
		Double Minimum { get; };
		Double Maximum { get; };
		Double Step { get; };
	}

	runtimeclass EffectParametersViewModel {
		UInt32 ScalingModeIdx;
		UInt32 EffectIdx;

		IVector<IInspectable> Params { get; };
	}
}
